### ISSUE TITLE
Methylation count file contains both 0s read counts and missing CpGs

### ISSUE THREAD

**Issue by moqri** [smithlabcode/dnmtools#117]
**Describe the bug**
It seems in some cases, the DNAm count files contains 0 total counts while in the same files there are some missing CpGs from the genome.

**To Reproduce**
 dnmtools counts -c <bam> -n -o <count file> -v

**Expected behavior**
Either all CpGs included and 0 reads be marked by 0 or all 0 reads be excluded from count file. Meaning all count files having the same CpGs or all count files having all the covered CpGs (counts>0). Currently, I am not sure what is the difference of 0 counts and being excluded for a CpG in the count file. 

**Screenshots**
<img width="208" alt="image" src="https://github.com/smithlabcode/dnmtools/assets/4342458/81590d57-f560-4683-9d5c-c2be97e1beb7">
<img width="563" alt="image" src="https://github.com/smithlabcode/dnmtools/assets/4342458/0e55a7a7-5003-4ffd-a7fc-d2b4ab49f197">

Thanks!

**Comment by andrewdavidsmith** [comment]
@moqri I recall this being a known bug some time ago. Can you confirm the version you are using? When this happened in the past, the CpG sites that were missing from the output were those that were not covered by reads and also appearing at the end of chromosomes, with no covered CpGs following them. I recall having fixed this, but maybe the bug is back again.

**Comment by moqri** [comment]
Sure thing: 
The version is dnmtools/1.2.2

And indeed it seems to be the ends of chromosomes: 
<img width="140" alt="image" src="https://github.com/smithlabcode/dnmtools/assets/4342458/ce12ada5-6f74-43a5-b9ac-759e127394b2">

**Comment by moqri** [comment]
This difference causes dnmtools diff function to give "ERROR:  bad order" (even after sorting both files)

**Comment by moqri** [comment]
The difference between reported CpGs in different files seem to also break the dnmtools diff command (it seems to break as soon as it sees a CpG in one file which is missing in the other)

**Comment by andrewdavidsmith** [comment]
@moqri Can you make a separate issue for the `diff` bug?

I figured out the problem. Any chromosome with no reads mapping to it is skipped. This strategy exists for a reason, but that reason is no longer important, so I will ensure all sites in all chromosomes are output, using the order in the BAM/SAM header.

**Comment by andrewdavidsmith** [comment]
Fixed with PR  #118
