### ISSUE TITLE
dnmtools diff  Error 

### ISSUE THREAD

**Issue by xies4** [smithlabcode/dnmtools#127]
**Is your feature request related to a problem? Please describe.**
I encountered the error below:
```
bad order:
chrom=chrUn_KI270315v1 [id=73] pos=89
appears after
chrom=chrUn_KI270315v1 [id=73] pos=829
```
Based on the post here https://github.com/smithlabcode/dnmtools/issues/42, it seems that the two input files have to have the same number of lines. 

**Describe the solution you'd like**
Add a subcommand to extract the rows of the shared positions. This will add intermediate files. 

**Describe alternatives you've considered**
In the code, don't assume that the two input files have the same number of lines. Not sure whether it's easy to be implemented. 

Thanks for your effort in developing dnmtools.

**Comment by andrewdavidsmith** [comment]
This seems like a bug report rather than a feature request: at minimum the docs should be more clear on the requirements of the data. But I'll try to solve this in the code as well to give a better error message at least. Or even allow missing sites in the input. Can you please provide the info requested from bug reports (version, how to reproduce, etc.)? You can do that by starting a new issue, select bug report, look at what's requested, and then paste it here, and cancel the new issue. That would accelerate this process. Thanks for your patience!

**Comment by andrewdavidsmith** [comment]
Fixed with PR #128. If the sites are sorted in consistent order between two files the intersection steps will be reported. The suggested tool might be helpful and extremely easy to build. It's almost identical to the GNU Unix comm command, which has very short source and is fast. @xies4 If you would use that tool even now that diff does what you seem to need, let me know with a separate issue. I'm closing this one as I think now diff solves your problem without creating the additional intermediate files.

**Comment by xies4** [comment]
Hi @andrewdavidsmith , sorry that I missed your first response. Thank you so much for your help.

**Comment by andrewdavidsmith** [comment]
This issue is resolved in the master branch and will be resolved in the next release.
