### ISSUE TITLE
roi "cannot sort data unless all data is loaded"

### ISSUE THREAD

**Issue by moqri** [smithlabcode/dnmtools#132]
**Describe the bug**
When I run roi with -s parameter, I get this error and I am not exactly sure what it means. 
"cannot sort data unless all data is loaded"

**To Reproduce**
1. produce unsorted hmrs
2. produce unsorted count data
3. run dnmtools roi -s <hmr> <count>

**Comment by andrewdavidsmith** [comment]
@moqri The "loaded" means reading all data from both files into memory before attempting the summary. It corresponds to the `-L` argument, like this:
```
$ dnmtools roi -s -L regions.bed methylome.counts.sym
```
If you have `regions.bed` with fewer than, say, 5000 lines, then it can be very much faster to *not* use `-L`. If you have over 100k lines, it's much faster to use `-L`. In the middle, it can depend, and probably when you have over 10k lines, it's faster to use `-L`.

As of PR #131 this has changed such that the regions can be sorted by quickly determining the chromosome order in `methylome.counts.sym` without loading the whole data into memory. So the mode of running `roi` that is fast for relatively few regions can now do the `-s`. I merged that on Friday, so let me know if you've done a pull since then becaese it would mean something was not finished. If you haven't updated recently, I suggest to try it.

I will do some tests to provide exact guidance on whether or not the `-L` is faster, but I still want to give people the option in case they are working on a laptop. If the `methylome.counts` is not `.sym` then it might fill the memory load it all in at once.

The reason these things are needed is that there has never been a consistent ordering for the chromosomes within reference genomes, and I don't think that problem will go away anytime soon.

**Comment by moqri** [comment]
Thanks you @andrewdavidsmith, indeed very helpful.

**Comment by andrewdavidsmith** [comment]
I'll close this issue with some data I pulled together on the relative performance of the two modes of running `roi`. Obviously these performance data would only matter if someone were either running large jobs or many small ones. Here `N` is the number of intervals, sampled from a set of intervals for the human genome hg38, with mean size 2237bp and the counts file had 30962770 lines, corresponding to CpG sites in hg38 including those in the "extra" chromosomes.

|     N | on disk | in memory |
|   ---:|     ---:|       ---:|
|    10 |  1.70 s |    9.55 s |
|   100 |  1.75 s |    9.43 s |
|  1000 |  2.05 s |    9.56 s |
| 10000 |  5.13 s |    9.64 s |
| 20000 |  8.49 s |    9.81 s |
| 30000 | 11.93 s |    9.83 s |
| 40000 | 15.20 s |   10.06 s |
| 50000 | 18.96 s |    9.95 s |
|    10 |  6.7 MB | 3079.7 MB |
| 50000 | 10.1 MB | 3084.0 MB |

Be aware that if you work on a cluster or in the cloud, latency of the disks might become a problem so the "in memory" option might be better all the way. This depends on how your storage is configured. Even if throughput is highly tuned, latency can cause major slowdown for the "on disk" mode.
