### ISSUE TITLE
Docs subdirectory

### ISSUE THREAD

**Issue by andrewdavidsmith** [smithlabcode/dnmtools#6]
The documentation subdirectory should be changed to docs in the future, as the documentation continues to be migrated to readthedocs from the previous latex/pdf format.

**Comment by masarunakajima** [comment]
I think the standard way to organize docs is having the `docs` directory in the root of the repo. We can simply remove the `documentation` directory and replace it with `docs`. The current `documentation/mkdocs.yml`, this can be moved to the root.  We just have to make a few changes to the current `.readthedocs.yaml` and the new 'mddocs.yml'. As for the current `documentation/README.md`, we can move it inside the new `docs`. However, this causes a warning during the readthedocs build. Since we have `strict: true` in `mkdocs.yml`, this warning makes the process abort. If we set `strict: false`, the build process ignores `docs/README.md` and builds successfully. So, if we want to keep this readme file, we have to either set `strict: false` or some other way, which I have not been able to find.

**Comment by andrewdavidsmith** [comment]
Closed with PR #47
